project_id = "rclpyipeytqbamiwcuih"

[functions.paypal-management]
verify_jwt = true

[functions.chat-management]
verify_jwt = true

[functions.extract-addon-context]
verify_jwt = true

[functions.admin-utilities]
verify_jwt = false

[functions.parse-character-card]
verify_jwt = true

[functions.get-character-memories]
verify_jwt = true