project_id = "rclpyipeytqbamiwcuih"

[functions.create-chat-with-greeting]
verify_jwt = true

[functions.create-basic-chat]
verify_jwt = true

[functions.paypal-management]
verify_jwt = true

[functions.create-credit-purchase]
verify_jwt = true

[functions.chat-management]
verify_jwt = true

[functions.finalize-credit-purchase]
verify_jwt = true

[functions.cleanup-contaminated-messages]
verify_jwt = true

[functions.chat-stream]
verify_jwt = true

[functions.extract-chat-context]
verify_jwt = true

[functions.monthly-credit-reset]
verify_jwt = false