// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rclpyipeytqbamiwcuih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbHB5aXBleXRxYmFtaXdjdWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDY0MjAsImV4cCI6MjA2NzMyMjQyMH0.D6IvUZBtLF5MdBGA2Re-1UMEc6bGaT2JhP0V1JuU_KU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export the URL for use in other parts of the app
export const SUPABASE_API_URL = SUPABASE_URL;

// Persona query interception & dedupe (dev only)
const originalFrom = supabase.from.bind(supabase);
const personaInFlight = new Map<string,string>();
// @ts-ignore
supabase.from = (table: string) => {
  if (table === 'personas') {
    try {
      const stack = new Error().stack?.split('\n').slice(2,8).join('\n') || '';
      const now = Date.now();
      // crude key using stack
      if (personaInFlight.has(stack)) {
        console.warn('[personas][dedupe] duplicate call within same tick suppressed signature hash');
      } else {
        personaInFlight.set(stack, String(now));
        setTimeout(()=> personaInFlight.delete(stack), 2000);
        console.log('[personas][call]', { when: now, stack });
      }
    } catch {}
  }
  return originalFrom(table);
};
